version: '3.7'
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:6875
      - DB_HOST=maria-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=mysql_password
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack-config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - maria-db
      
  maria-db:
    image: lscr.io/linuxserver/mariadb
    container_name: maria-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mysql_password
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=mysql_password
    volumes:
      - bookstack-db-config:/config
    restart: unless-stopped
    
volumes:
  bookstack-config:
  bookstack-db-config:
  
