services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongo-data:/data/db
      - mongo-config-db:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_password
      - ME_CONFIG_MONGODB_URL=mongodb://mongo_user:mongo_password@mongo:27017/?authSource=admin
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:
  mongo-data:
  mongo-config-db:

