version: '3.7'
services:
  dynamo-db:
    image:  amazon/dynamodb-local
    container_name: dynamo-db
    restart: always
    volumes:
      -  dynamodb_data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    
  dynamodb-manager:
    image:  taydy/dynamodb-manager
    container_name: dynamodb-manager
    restart: always
    ports:
      - 8080:80
      
      
volumes:
  dynamodb_data:
  
