version: '3'

services:

  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin-password
      POSTGRES_DB: bitnami_keycloak
    volumes:
      - 'postgresql-data:/bitnami/postgresql'
      - 'postgresql-preinitdb:/docker-entrypoint-preinitdb.d'
      - 'postgresql-initdb:/docker-entrypoint-initdb.d'

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - 'pgadmin:/var/lib/pgadmin'

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=key_admin
      - KEYCLOAK_ADMIN_PASSWORD=key_password
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin-password
    depends_on:
      - postgresql

volumes:
  postgresql-data:
  postgresql-preinitdb:
  postgresql-initdb:
  pgadmin:
