version: "3.8"
services:
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
